// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/twitter-srv/proto/api/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/twitter-srv/proto/api/api.proto

It has these top-level messages:
	Point
	Contributor
	Coordinates
	Hashtag
	Url
	Mention
	MediaSize
	Sizes
	Variant
	VideoInfo
	Media
	Entities
	BoundingBox
	ContainedWithin
	Place
	Tweet
	User
	TweetRequest
	TweetResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng" json:"lng,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Contributor struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IdStr      string `protobuf:"bytes,2,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
	ScreenName string `protobuf:"bytes,3,opt,name=screen_name,json=screenName" json:"screen_name,omitempty"`
}

func (m *Contributor) Reset()                    { *m = Contributor{} }
func (m *Contributor) String() string            { return proto.CompactTextString(m) }
func (*Contributor) ProtoMessage()               {}
func (*Contributor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Contributor) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contributor) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *Contributor) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

type Coordinates struct {
	Coordinates []float64 `protobuf:"fixed64,1,rep,packed,name=coordinates" json:"coordinates,omitempty"`
	Type        string    `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *Coordinates) Reset()                    { *m = Coordinates{} }
func (m *Coordinates) String() string            { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()               {}
func (*Coordinates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Coordinates) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Coordinates) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Hashtag struct {
	Indices []int64 `protobuf:"varint,1,rep,packed,name=indices" json:"indices,omitempty"`
	Text    string  `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *Hashtag) Reset()                    { *m = Hashtag{} }
func (m *Hashtag) String() string            { return proto.CompactTextString(m) }
func (*Hashtag) ProtoMessage()               {}
func (*Hashtag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Hashtag) GetIndices() []int64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Hashtag) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Url struct {
	Indices     []int64 `protobuf:"varint,1,rep,packed,name=indices" json:"indices,omitempty"`
	Url         string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	DisplayUrl  string  `protobuf:"bytes,3,opt,name=display_url,json=displayUrl" json:"display_url,omitempty"`
	ExpandedUrl string  `protobuf:"bytes,4,opt,name=expanded_url,json=expandedUrl" json:"expanded_url,omitempty"`
}

func (m *Url) Reset()                    { *m = Url{} }
func (m *Url) String() string            { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()               {}
func (*Url) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Url) GetIndices() []int64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Url) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Url) GetDisplayUrl() string {
	if m != nil {
		return m.DisplayUrl
	}
	return ""
}

func (m *Url) GetExpandedUrl() string {
	if m != nil {
		return m.ExpandedUrl
	}
	return ""
}

type Mention struct {
	Name       string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Indices    []int64 `protobuf:"varint,2,rep,packed,name=indices" json:"indices,omitempty"`
	ScreenName string  `protobuf:"bytes,3,opt,name=screen_name,json=screenName" json:"screen_name,omitempty"`
	Id         int64   `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	IdStr      string  `protobuf:"bytes,5,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
}

func (m *Mention) Reset()                    { *m = Mention{} }
func (m *Mention) String() string            { return proto.CompactTextString(m) }
func (*Mention) ProtoMessage()               {}
func (*Mention) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Mention) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mention) GetIndices() []int64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Mention) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *Mention) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mention) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

type MediaSize struct {
	W      int64  `protobuf:"varint,1,opt,name=w" json:"w,omitempty"`
	H      int64  `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Resize string `protobuf:"bytes,3,opt,name=resize" json:"resize,omitempty"`
}

func (m *MediaSize) Reset()                    { *m = MediaSize{} }
func (m *MediaSize) String() string            { return proto.CompactTextString(m) }
func (*MediaSize) ProtoMessage()               {}
func (*MediaSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MediaSize) GetW() int64 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *MediaSize) GetH() int64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *MediaSize) GetResize() string {
	if m != nil {
		return m.Resize
	}
	return ""
}

type Sizes struct {
	Medium *MediaSize `protobuf:"bytes,1,opt,name=medium" json:"medium,omitempty"`
	Thumb  *MediaSize `protobuf:"bytes,2,opt,name=thumb" json:"thumb,omitempty"`
	Small  *MediaSize `protobuf:"bytes,3,opt,name=small" json:"small,omitempty"`
	Large  *MediaSize `protobuf:"bytes,4,opt,name=large" json:"large,omitempty"`
}

func (m *Sizes) Reset()                    { *m = Sizes{} }
func (m *Sizes) String() string            { return proto.CompactTextString(m) }
func (*Sizes) ProtoMessage()               {}
func (*Sizes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Sizes) GetMedium() *MediaSize {
	if m != nil {
		return m.Medium
	}
	return nil
}

func (m *Sizes) GetThumb() *MediaSize {
	if m != nil {
		return m.Thumb
	}
	return nil
}

func (m *Sizes) GetSmall() *MediaSize {
	if m != nil {
		return m.Small
	}
	return nil
}

func (m *Sizes) GetLarge() *MediaSize {
	if m != nil {
		return m.Large
	}
	return nil
}

type Variant struct {
	Bitrate     int64  `protobuf:"varint,1,opt,name=bitrate" json:"bitrate,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (m *Variant) Reset()                    { *m = Variant{} }
func (m *Variant) String() string            { return proto.CompactTextString(m) }
func (*Variant) ProtoMessage()               {}
func (*Variant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Variant) GetBitrate() int64 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *Variant) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Variant) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type VideoInfo struct {
	AspectRatio    []int64    `protobuf:"varint,1,rep,packed,name=aspect_ratio,json=aspectRatio" json:"aspect_ratio,omitempty"`
	DurationMillis int64      `protobuf:"varint,2,opt,name=duration_millis,json=durationMillis" json:"duration_millis,omitempty"`
	Variants       []*Variant `protobuf:"bytes,3,rep,name=variants" json:"variants,omitempty"`
}

func (m *VideoInfo) Reset()                    { *m = VideoInfo{} }
func (m *VideoInfo) String() string            { return proto.CompactTextString(m) }
func (*VideoInfo) ProtoMessage()               {}
func (*VideoInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *VideoInfo) GetAspectRatio() []int64 {
	if m != nil {
		return m.AspectRatio
	}
	return nil
}

func (m *VideoInfo) GetDurationMillis() int64 {
	if m != nil {
		return m.DurationMillis
	}
	return 0
}

func (m *VideoInfo) GetVariants() []*Variant {
	if m != nil {
		return m.Variants
	}
	return nil
}

type Media struct {
	Id                int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IdStr             string     `protobuf:"bytes,2,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
	MediaUrl          string     `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl" json:"media_url,omitempty"`
	MediaUrlHttps     string     `protobuf:"bytes,4,opt,name=media_url_https,json=mediaUrlHttps" json:"media_url_https,omitempty"`
	Url               string     `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	DisplayUrl        string     `protobuf:"bytes,6,opt,name=display_url,json=displayUrl" json:"display_url,omitempty"`
	ExpandedUrl       string     `protobuf:"bytes,7,opt,name=expanded_url,json=expandedUrl" json:"expanded_url,omitempty"`
	Sizes             *Sizes     `protobuf:"bytes,8,opt,name=sizes" json:"sizes,omitempty"`
	SourceStatusId    int64      `protobuf:"varint,9,opt,name=source_status_id,json=sourceStatusId" json:"source_status_id,omitempty"`
	SourceStatusIdStr string     `protobuf:"bytes,10,opt,name=source_status_id_str,json=sourceStatusIdStr" json:"source_status_id_str,omitempty"`
	Type              string     `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Indices           []int64    `protobuf:"varint,12,rep,packed,name=indices" json:"indices,omitempty"`
	VideoInfo         *VideoInfo `protobuf:"bytes,13,opt,name=video_info,json=videoInfo" json:"video_info,omitempty"`
}

func (m *Media) Reset()                    { *m = Media{} }
func (m *Media) String() string            { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()               {}
func (*Media) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Media) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Media) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *Media) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *Media) GetMediaUrlHttps() string {
	if m != nil {
		return m.MediaUrlHttps
	}
	return ""
}

func (m *Media) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Media) GetDisplayUrl() string {
	if m != nil {
		return m.DisplayUrl
	}
	return ""
}

func (m *Media) GetExpandedUrl() string {
	if m != nil {
		return m.ExpandedUrl
	}
	return ""
}

func (m *Media) GetSizes() *Sizes {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *Media) GetSourceStatusId() int64 {
	if m != nil {
		return m.SourceStatusId
	}
	return 0
}

func (m *Media) GetSourceStatusIdStr() string {
	if m != nil {
		return m.SourceStatusIdStr
	}
	return ""
}

func (m *Media) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Media) GetIndices() []int64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Media) GetVideoInfo() *VideoInfo {
	if m != nil {
		return m.VideoInfo
	}
	return nil
}

type Entities struct {
	Hashtags     []*Hashtag `protobuf:"bytes,1,rep,name=hashtags" json:"hashtags,omitempty"`
	Urls         []*Url     `protobuf:"bytes,2,rep,name=urls" json:"urls,omitempty"`
	Url          *Url       `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	UserMentions []*Mention `protobuf:"bytes,4,rep,name=user_mentions,json=userMentions" json:"user_mentions,omitempty"`
	Media        []*Media   `protobuf:"bytes,5,rep,name=media" json:"media,omitempty"`
}

func (m *Entities) Reset()                    { *m = Entities{} }
func (m *Entities) String() string            { return proto.CompactTextString(m) }
func (*Entities) ProtoMessage()               {}
func (*Entities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Entities) GetHashtags() []*Hashtag {
	if m != nil {
		return m.Hashtags
	}
	return nil
}

func (m *Entities) GetUrls() []*Url {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Entities) GetUrl() *Url {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *Entities) GetUserMentions() []*Mention {
	if m != nil {
		return m.UserMentions
	}
	return nil
}

func (m *Entities) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type BoundingBox struct {
	Coordinates []*Coordinates `protobuf:"bytes,1,rep,name=coordinates" json:"coordinates,omitempty"`
	Type        string         `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *BoundingBox) Reset()                    { *m = BoundingBox{} }
func (m *BoundingBox) String() string            { return proto.CompactTextString(m) }
func (*BoundingBox) ProtoMessage()               {}
func (*BoundingBox) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *BoundingBox) GetCoordinates() []*Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *BoundingBox) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ContainedWithin struct {
	Attributes  map[string]string `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BoundingBox *BoundingBox      `protobuf:"bytes,2,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
	Country     string            `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	CountryCode string            `protobuf:"bytes,4,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	FullName    string            `protobuf:"bytes,5,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Id          string            `protobuf:"bytes,6,opt,name=id" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	PlaceType   string            `protobuf:"bytes,8,opt,name=place_type,json=placeType" json:"place_type,omitempty"`
	Url         string            `protobuf:"bytes,9,opt,name=url" json:"url,omitempty"`
}

func (m *ContainedWithin) Reset()                    { *m = ContainedWithin{} }
func (m *ContainedWithin) String() string            { return proto.CompactTextString(m) }
func (*ContainedWithin) ProtoMessage()               {}
func (*ContainedWithin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ContainedWithin) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ContainedWithin) GetBoundingBox() *BoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *ContainedWithin) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ContainedWithin) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *ContainedWithin) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *ContainedWithin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainedWithin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainedWithin) GetPlaceType() string {
	if m != nil {
		return m.PlaceType
	}
	return ""
}

func (m *ContainedWithin) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Place struct {
	Attributes      map[string]string  `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BoundingBox     *BoundingBox       `protobuf:"bytes,2,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
	ContainedWithin []*ContainedWithin `protobuf:"bytes,3,rep,name=contained_within,json=containedWithin" json:"contained_within,omitempty"`
	Country         string             `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	CountryCode     string             `protobuf:"bytes,5,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	FullName        string             `protobuf:"bytes,6,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Geometry        *BoundingBox       `protobuf:"bytes,7,opt,name=geometry" json:"geometry,omitempty"`
	Id              string             `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	Name            string             `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	PlaceType       string             `protobuf:"bytes,10,opt,name=place_type,json=placeType" json:"place_type,omitempty"`
	Polylines       []string           `protobuf:"bytes,11,rep,name=polylines" json:"polylines,omitempty"`
	Url             string             `protobuf:"bytes,12,opt,name=url" json:"url,omitempty"`
}

func (m *Place) Reset()                    { *m = Place{} }
func (m *Place) String() string            { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()               {}
func (*Place) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Place) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Place) GetBoundingBox() *BoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *Place) GetContainedWithin() []*ContainedWithin {
	if m != nil {
		return m.ContainedWithin
	}
	return nil
}

func (m *Place) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Place) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Place) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Place) GetGeometry() *BoundingBox {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Place) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetPlaceType() string {
	if m != nil {
		return m.PlaceType
	}
	return ""
}

func (m *Place) GetPolylines() []string {
	if m != nil {
		return m.Polylines
	}
	return nil
}

func (m *Place) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Tweet struct {
	Contributors         []*Contributor    `protobuf:"bytes,1,rep,name=contributors" json:"contributors,omitempty"`
	Coordinates          *Coordinates      `protobuf:"bytes,2,opt,name=coordinates" json:"coordinates,omitempty"`
	CreatedAt            string            `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Entities             *Entities         `protobuf:"bytes,4,opt,name=entities" json:"entities,omitempty"`
	ExtendedEntities     *Entities         `protobuf:"bytes,5,opt,name=extended_entities,json=extendedEntities" json:"extended_entities,omitempty"`
	FavoriteCount        int64             `protobuf:"varint,6,opt,name=favorite_count,json=favoriteCount" json:"favorite_count,omitempty"`
	Favorited            bool              `protobuf:"varint,7,opt,name=favorited" json:"favorited,omitempty"`
	FilterLevel          string            `protobuf:"bytes,8,opt,name=filter_level,json=filterLevel" json:"filter_level,omitempty"`
	Id                   int64             `protobuf:"varint,9,opt,name=id" json:"id,omitempty"`
	IdStr                string            `protobuf:"bytes,10,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
	InReplyToScreenName  string            `protobuf:"bytes,11,opt,name=in_reply_to_screen_name,json=inReplyToScreenName" json:"in_reply_to_screen_name,omitempty"`
	InReplyToStatusId    int64             `protobuf:"varint,12,opt,name=in_reply_to_status_id,json=inReplyToStatusId" json:"in_reply_to_status_id,omitempty"`
	InReplyToStatusIdStr string            `protobuf:"bytes,13,opt,name=in_reply_to_status_id_str,json=inReplyToStatusIdStr" json:"in_reply_to_status_id_str,omitempty"`
	InReplyToUserId      int64             `protobuf:"varint,14,opt,name=in_reply_to_user_id,json=inReplyToUserId" json:"in_reply_to_user_id,omitempty"`
	InReplyToUserIdStr   string            `protobuf:"bytes,15,opt,name=in_reply_to_user_id_str,json=inReplyToUserIdStr" json:"in_reply_to_user_id_str,omitempty"`
	Lang                 string            `protobuf:"bytes,16,opt,name=lang" json:"lang,omitempty"`
	Place                *Place            `protobuf:"bytes,17,opt,name=place" json:"place,omitempty"`
	PossiblySensitive    bool              `protobuf:"varint,18,opt,name=possibly_sensitive,json=possiblySensitive" json:"possibly_sensitive,omitempty"`
	RetweetCount         int64             `protobuf:"varint,19,opt,name=retweet_count,json=retweetCount" json:"retweet_count,omitempty"`
	Retweeted            bool              `protobuf:"varint,20,opt,name=retweeted" json:"retweeted,omitempty"`
	RetweetedStatus      *Tweet            `protobuf:"bytes,21,opt,name=retweeted_status,json=retweetedStatus" json:"retweeted_status,omitempty"`
	Source               string            `protobuf:"bytes,22,opt,name=source" json:"source,omitempty"`
	Scopes               map[string]string `protobuf:"bytes,23,rep,name=scopes" json:"scopes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Text                 string            `protobuf:"bytes,24,opt,name=text" json:"text,omitempty"`
	Truncated            bool              `protobuf:"varint,25,opt,name=truncated" json:"truncated,omitempty"`
	User                 *User             `protobuf:"bytes,26,opt,name=user" json:"user,omitempty"`
	WithheldCopyright    bool              `protobuf:"varint,27,opt,name=withheld_copyright,json=withheldCopyright" json:"withheld_copyright,omitempty"`
	WithheldInCountries  []string          `protobuf:"bytes,28,rep,name=withheld_in_countries,json=withheldInCountries" json:"withheld_in_countries,omitempty"`
	WithheldScope        string            `protobuf:"bytes,29,opt,name=withheld_scope,json=withheldScope" json:"withheld_scope,omitempty"`
}

func (m *Tweet) Reset()                    { *m = Tweet{} }
func (m *Tweet) String() string            { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()               {}
func (*Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Tweet) GetContributors() []*Contributor {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *Tweet) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Tweet) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Tweet) GetEntities() *Entities {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *Tweet) GetExtendedEntities() *Entities {
	if m != nil {
		return m.ExtendedEntities
	}
	return nil
}

func (m *Tweet) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *Tweet) GetFavorited() bool {
	if m != nil {
		return m.Favorited
	}
	return false
}

func (m *Tweet) GetFilterLevel() string {
	if m != nil {
		return m.FilterLevel
	}
	return ""
}

func (m *Tweet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tweet) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *Tweet) GetInReplyToScreenName() string {
	if m != nil {
		return m.InReplyToScreenName
	}
	return ""
}

func (m *Tweet) GetInReplyToStatusId() int64 {
	if m != nil {
		return m.InReplyToStatusId
	}
	return 0
}

func (m *Tweet) GetInReplyToStatusIdStr() string {
	if m != nil {
		return m.InReplyToStatusIdStr
	}
	return ""
}

func (m *Tweet) GetInReplyToUserId() int64 {
	if m != nil {
		return m.InReplyToUserId
	}
	return 0
}

func (m *Tweet) GetInReplyToUserIdStr() string {
	if m != nil {
		return m.InReplyToUserIdStr
	}
	return ""
}

func (m *Tweet) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Tweet) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *Tweet) GetPossiblySensitive() bool {
	if m != nil {
		return m.PossiblySensitive
	}
	return false
}

func (m *Tweet) GetRetweetCount() int64 {
	if m != nil {
		return m.RetweetCount
	}
	return 0
}

func (m *Tweet) GetRetweeted() bool {
	if m != nil {
		return m.Retweeted
	}
	return false
}

func (m *Tweet) GetRetweetedStatus() *Tweet {
	if m != nil {
		return m.RetweetedStatus
	}
	return nil
}

func (m *Tweet) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Tweet) GetScopes() map[string]string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Tweet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Tweet) GetTruncated() bool {
	if m != nil {
		return m.Truncated
	}
	return false
}

func (m *Tweet) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Tweet) GetWithheldCopyright() bool {
	if m != nil {
		return m.WithheldCopyright
	}
	return false
}

func (m *Tweet) GetWithheldInCountries() []string {
	if m != nil {
		return m.WithheldInCountries
	}
	return nil
}

func (m *Tweet) GetWithheldScope() string {
	if m != nil {
		return m.WithheldScope
	}
	return ""
}

type User struct {
	ContributorsEnabled            bool      `protobuf:"varint,1,opt,name=contributors_enabled,json=contributorsEnabled" json:"contributors_enabled,omitempty"`
	CreatedAt                      string    `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	DefaultProfile                 bool      `protobuf:"varint,3,opt,name=default_profile,json=defaultProfile" json:"default_profile,omitempty"`
	DefaultProfileImage            bool      `protobuf:"varint,4,opt,name=default_profile_image,json=defaultProfileImage" json:"default_profile_image,omitempty"`
	Description                    string    `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Entities                       *Entities `protobuf:"bytes,6,opt,name=entities" json:"entities,omitempty"`
	FavouritesCount                int64     `protobuf:"varint,7,opt,name=favourites_count,json=favouritesCount" json:"favourites_count,omitempty"`
	FollowRequestSent              bool      `protobuf:"varint,8,opt,name=follow_request_sent,json=followRequestSent" json:"follow_request_sent,omitempty"`
	FollowersCount                 int64     `protobuf:"varint,9,opt,name=followers_count,json=followersCount" json:"followers_count,omitempty"`
	Following                      bool      `protobuf:"varint,10,opt,name=following" json:"following,omitempty"`
	FriendsCount                   int64     `protobuf:"varint,11,opt,name=friends_count,json=friendsCount" json:"friends_count,omitempty"`
	GeoEnabled                     bool      `protobuf:"varint,12,opt,name=geo_enabled,json=geoEnabled" json:"geo_enabled,omitempty"`
	Id                             int64     `protobuf:"varint,13,opt,name=id" json:"id,omitempty"`
	IdStr                          string    `protobuf:"bytes,14,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
	IsTranslator                   bool      `protobuf:"varint,15,opt,name=is_translator,json=isTranslator" json:"is_translator,omitempty"`
	Lang                           string    `protobuf:"bytes,16,opt,name=lang" json:"lang,omitempty"`
	ListedCount                    int64     `protobuf:"varint,17,opt,name=listed_count,json=listedCount" json:"listed_count,omitempty"`
	Location                       string    `protobuf:"bytes,18,opt,name=location" json:"location,omitempty"`
	Name                           string    `protobuf:"bytes,19,opt,name=name" json:"name,omitempty"`
	Notifications                  bool      `protobuf:"varint,20,opt,name=notifications" json:"notifications,omitempty"`
	ProfileBackgroundColor         string    `protobuf:"bytes,21,opt,name=profile_background_color,json=profileBackgroundColor" json:"profile_background_color,omitempty"`
	ProfileBackgroundImageUrl      string    `protobuf:"bytes,22,opt,name=profile_background_image_url,json=profileBackgroundImageUrl" json:"profile_background_image_url,omitempty"`
	ProfileBackgroundImageUrlHttps string    `protobuf:"bytes,23,opt,name=profile_background_image_url_https,json=profileBackgroundImageUrlHttps" json:"profile_background_image_url_https,omitempty"`
	ProfileBackgroundTile          bool      `protobuf:"varint,24,opt,name=profile_background_tile,json=profileBackgroundTile" json:"profile_background_tile,omitempty"`
	ProfileBannerUrl               string    `protobuf:"bytes,25,opt,name=profile_banner_url,json=profileBannerUrl" json:"profile_banner_url,omitempty"`
	ProfileImageUrl                string    `protobuf:"bytes,26,opt,name=profile_image_url,json=profileImageUrl" json:"profile_image_url,omitempty"`
	ProfileImageUrlHttps           string    `protobuf:"bytes,27,opt,name=profile_image_url_https,json=profileImageUrlHttps" json:"profile_image_url_https,omitempty"`
	ProfileLinkColor               string    `protobuf:"bytes,28,opt,name=profile_link_color,json=profileLinkColor" json:"profile_link_color,omitempty"`
	ProfileSidebarBorderColor      string    `protobuf:"bytes,29,opt,name=profile_sidebar_border_color,json=profileSidebarBorderColor" json:"profile_sidebar_border_color,omitempty"`
	ProfileSidebarFillColor        string    `protobuf:"bytes,30,opt,name=profile_sidebar_fill_color,json=profileSidebarFillColor" json:"profile_sidebar_fill_color,omitempty"`
	ProfileTextColor               string    `protobuf:"bytes,31,opt,name=profile_text_color,json=profileTextColor" json:"profile_text_color,omitempty"`
	ProfileUseBackgroundImage      bool      `protobuf:"varint,32,opt,name=profile_use_background_image,json=profileUseBackgroundImage" json:"profile_use_background_image,omitempty"`
	Protected                      bool      `protobuf:"varint,33,opt,name=protected" json:"protected,omitempty"`
	ScreenName                     string    `protobuf:"bytes,34,opt,name=screen_name,json=screenName" json:"screen_name,omitempty"`
	ShowAllInlineMedia             bool      `protobuf:"varint,35,opt,name=show_all_inline_media,json=showAllInlineMedia" json:"show_all_inline_media,omitempty"`
	Status                         *Tweet    `protobuf:"bytes,36,opt,name=status" json:"status,omitempty"`
	StatusesCount                  int64     `protobuf:"varint,37,opt,name=statuses_count,json=statusesCount" json:"statuses_count,omitempty"`
	TimeZone                       string    `protobuf:"bytes,38,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
	Url                            string    `protobuf:"bytes,39,opt,name=url" json:"url,omitempty"`
	UtcOffset                      int64     `protobuf:"varint,40,opt,name=utc_offset,json=utcOffset" json:"utc_offset,omitempty"`
	Verified                       bool      `protobuf:"varint,41,opt,name=verified" json:"verified,omitempty"`
	WithheldInCountries            []string  `protobuf:"bytes,42,rep,name=withheld_in_countries,json=withheldInCountries" json:"withheld_in_countries,omitempty"`
	WithheldScope                  string    `protobuf:"bytes,43,opt,name=withheld_scope,json=withheldScope" json:"withheld_scope,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *User) GetContributorsEnabled() bool {
	if m != nil {
		return m.ContributorsEnabled
	}
	return false
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetDefaultProfile() bool {
	if m != nil {
		return m.DefaultProfile
	}
	return false
}

func (m *User) GetDefaultProfileImage() bool {
	if m != nil {
		return m.DefaultProfileImage
	}
	return false
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetEntities() *Entities {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *User) GetFavouritesCount() int64 {
	if m != nil {
		return m.FavouritesCount
	}
	return 0
}

func (m *User) GetFollowRequestSent() bool {
	if m != nil {
		return m.FollowRequestSent
	}
	return false
}

func (m *User) GetFollowersCount() int64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *User) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

func (m *User) GetFriendsCount() int64 {
	if m != nil {
		return m.FriendsCount
	}
	return 0
}

func (m *User) GetGeoEnabled() bool {
	if m != nil {
		return m.GeoEnabled
	}
	return false
}

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *User) GetIsTranslator() bool {
	if m != nil {
		return m.IsTranslator
	}
	return false
}

func (m *User) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *User) GetListedCount() int64 {
	if m != nil {
		return m.ListedCount
	}
	return 0
}

func (m *User) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNotifications() bool {
	if m != nil {
		return m.Notifications
	}
	return false
}

func (m *User) GetProfileBackgroundColor() string {
	if m != nil {
		return m.ProfileBackgroundColor
	}
	return ""
}

func (m *User) GetProfileBackgroundImageUrl() string {
	if m != nil {
		return m.ProfileBackgroundImageUrl
	}
	return ""
}

func (m *User) GetProfileBackgroundImageUrlHttps() string {
	if m != nil {
		return m.ProfileBackgroundImageUrlHttps
	}
	return ""
}

func (m *User) GetProfileBackgroundTile() bool {
	if m != nil {
		return m.ProfileBackgroundTile
	}
	return false
}

func (m *User) GetProfileBannerUrl() string {
	if m != nil {
		return m.ProfileBannerUrl
	}
	return ""
}

func (m *User) GetProfileImageUrl() string {
	if m != nil {
		return m.ProfileImageUrl
	}
	return ""
}

func (m *User) GetProfileImageUrlHttps() string {
	if m != nil {
		return m.ProfileImageUrlHttps
	}
	return ""
}

func (m *User) GetProfileLinkColor() string {
	if m != nil {
		return m.ProfileLinkColor
	}
	return ""
}

func (m *User) GetProfileSidebarBorderColor() string {
	if m != nil {
		return m.ProfileSidebarBorderColor
	}
	return ""
}

func (m *User) GetProfileSidebarFillColor() string {
	if m != nil {
		return m.ProfileSidebarFillColor
	}
	return ""
}

func (m *User) GetProfileTextColor() string {
	if m != nil {
		return m.ProfileTextColor
	}
	return ""
}

func (m *User) GetProfileUseBackgroundImage() bool {
	if m != nil {
		return m.ProfileUseBackgroundImage
	}
	return false
}

func (m *User) GetProtected() bool {
	if m != nil {
		return m.Protected
	}
	return false
}

func (m *User) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *User) GetShowAllInlineMedia() bool {
	if m != nil {
		return m.ShowAllInlineMedia
	}
	return false
}

func (m *User) GetStatus() *Tweet {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *User) GetStatusesCount() int64 {
	if m != nil {
		return m.StatusesCount
	}
	return 0
}

func (m *User) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *User) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *User) GetUtcOffset() int64 {
	if m != nil {
		return m.UtcOffset
	}
	return 0
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetWithheldInCountries() []string {
	if m != nil {
		return m.WithheldInCountries
	}
	return nil
}

func (m *User) GetWithheldScope() string {
	if m != nil {
		return m.WithheldScope
	}
	return ""
}

type TweetRequest struct {
	Status             string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	InReplyToStatusId  uint64   `protobuf:"varint,2,opt,name=in_reply_to_status_id,json=inReplyToStatusId" json:"in_reply_to_status_id,omitempty"`
	PossiblySensitive  bool     `protobuf:"varint,3,opt,name=possibly_sensitive,json=possiblySensitive" json:"possibly_sensitive,omitempty"`
	LatLng             *Point   `protobuf:"bytes,4,opt,name=lat_lng,json=latLng" json:"lat_lng,omitempty"`
	PlaceId            string   `protobuf:"bytes,5,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	DisplayCoordinates bool     `protobuf:"varint,6,opt,name=display_coordinates,json=displayCoordinates" json:"display_coordinates,omitempty"`
	TrimUser           bool     `protobuf:"varint,7,opt,name=trim_user,json=trimUser" json:"trim_user,omitempty"`
	MediaIds           []uint64 `protobuf:"varint,8,rep,packed,name=media_ids,json=mediaIds" json:"media_ids,omitempty"`
}

func (m *TweetRequest) Reset()                    { *m = TweetRequest{} }
func (m *TweetRequest) String() string            { return proto.CompactTextString(m) }
func (*TweetRequest) ProtoMessage()               {}
func (*TweetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TweetRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TweetRequest) GetInReplyToStatusId() uint64 {
	if m != nil {
		return m.InReplyToStatusId
	}
	return 0
}

func (m *TweetRequest) GetPossiblySensitive() bool {
	if m != nil {
		return m.PossiblySensitive
	}
	return false
}

func (m *TweetRequest) GetLatLng() *Point {
	if m != nil {
		return m.LatLng
	}
	return nil
}

func (m *TweetRequest) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *TweetRequest) GetDisplayCoordinates() bool {
	if m != nil {
		return m.DisplayCoordinates
	}
	return false
}

func (m *TweetRequest) GetTrimUser() bool {
	if m != nil {
		return m.TrimUser
	}
	return false
}

func (m *TweetRequest) GetMediaIds() []uint64 {
	if m != nil {
		return m.MediaIds
	}
	return nil
}

type TweetResponse struct {
	Contributors         []*Contributor    `protobuf:"bytes,1,rep,name=contributors" json:"contributors,omitempty"`
	Coordinates          *Coordinates      `protobuf:"bytes,2,opt,name=coordinates" json:"coordinates,omitempty"`
	CreatedAt            string            `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Entities             *Entities         `protobuf:"bytes,4,opt,name=entities" json:"entities,omitempty"`
	ExtendedEntities     *Entities         `protobuf:"bytes,5,opt,name=extended_entities,json=extendedEntities" json:"extended_entities,omitempty"`
	FavoriteCount        int64             `protobuf:"varint,6,opt,name=favorite_count,json=favoriteCount" json:"favorite_count,omitempty"`
	Favorited            bool              `protobuf:"varint,7,opt,name=favorited" json:"favorited,omitempty"`
	FilterLevel          string            `protobuf:"bytes,8,opt,name=filter_level,json=filterLevel" json:"filter_level,omitempty"`
	Id                   int64             `protobuf:"varint,9,opt,name=id" json:"id,omitempty"`
	IdStr                string            `protobuf:"bytes,10,opt,name=id_str,json=idStr" json:"id_str,omitempty"`
	InReplyToScreenName  string            `protobuf:"bytes,11,opt,name=in_reply_to_screen_name,json=inReplyToScreenName" json:"in_reply_to_screen_name,omitempty"`
	InReplyToStatusId    int64             `protobuf:"varint,12,opt,name=in_reply_to_status_id,json=inReplyToStatusId" json:"in_reply_to_status_id,omitempty"`
	InReplyToStatusIdStr string            `protobuf:"bytes,13,opt,name=in_reply_to_status_id_str,json=inReplyToStatusIdStr" json:"in_reply_to_status_id_str,omitempty"`
	InReplyToUserId      int64             `protobuf:"varint,14,opt,name=in_reply_to_user_id,json=inReplyToUserId" json:"in_reply_to_user_id,omitempty"`
	InReplyToUserIdStr   string            `protobuf:"bytes,15,opt,name=in_reply_to_user_id_str,json=inReplyToUserIdStr" json:"in_reply_to_user_id_str,omitempty"`
	Lang                 string            `protobuf:"bytes,16,opt,name=lang" json:"lang,omitempty"`
	Place                *Place            `protobuf:"bytes,17,opt,name=place" json:"place,omitempty"`
	PossiblySensitive    bool              `protobuf:"varint,18,opt,name=possibly_sensitive,json=possiblySensitive" json:"possibly_sensitive,omitempty"`
	RetweetCount         int64             `protobuf:"varint,19,opt,name=retweet_count,json=retweetCount" json:"retweet_count,omitempty"`
	Retweeted            bool              `protobuf:"varint,20,opt,name=retweeted" json:"retweeted,omitempty"`
	RetweetedStatus      *Tweet            `protobuf:"bytes,21,opt,name=retweeted_status,json=retweetedStatus" json:"retweeted_status,omitempty"`
	Source               string            `protobuf:"bytes,22,opt,name=source" json:"source,omitempty"`
	Scopes               map[string]string `protobuf:"bytes,23,rep,name=scopes" json:"scopes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Text                 string            `protobuf:"bytes,24,opt,name=text" json:"text,omitempty"`
	Truncated            bool              `protobuf:"varint,25,opt,name=truncated" json:"truncated,omitempty"`
	User                 *User             `protobuf:"bytes,26,opt,name=user" json:"user,omitempty"`
	WithheldCopyright    bool              `protobuf:"varint,27,opt,name=withheld_copyright,json=withheldCopyright" json:"withheld_copyright,omitempty"`
	WithheldInCountries  []string          `protobuf:"bytes,28,rep,name=withheld_in_countries,json=withheldInCountries" json:"withheld_in_countries,omitempty"`
	WithheldScope        string            `protobuf:"bytes,29,opt,name=withheld_scope,json=withheldScope" json:"withheld_scope,omitempty"`
}

func (m *TweetResponse) Reset()                    { *m = TweetResponse{} }
func (m *TweetResponse) String() string            { return proto.CompactTextString(m) }
func (*TweetResponse) ProtoMessage()               {}
func (*TweetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TweetResponse) GetContributors() []*Contributor {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *TweetResponse) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *TweetResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TweetResponse) GetEntities() *Entities {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *TweetResponse) GetExtendedEntities() *Entities {
	if m != nil {
		return m.ExtendedEntities
	}
	return nil
}

func (m *TweetResponse) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *TweetResponse) GetFavorited() bool {
	if m != nil {
		return m.Favorited
	}
	return false
}

func (m *TweetResponse) GetFilterLevel() string {
	if m != nil {
		return m.FilterLevel
	}
	return ""
}

func (m *TweetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TweetResponse) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *TweetResponse) GetInReplyToScreenName() string {
	if m != nil {
		return m.InReplyToScreenName
	}
	return ""
}

func (m *TweetResponse) GetInReplyToStatusId() int64 {
	if m != nil {
		return m.InReplyToStatusId
	}
	return 0
}

func (m *TweetResponse) GetInReplyToStatusIdStr() string {
	if m != nil {
		return m.InReplyToStatusIdStr
	}
	return ""
}

func (m *TweetResponse) GetInReplyToUserId() int64 {
	if m != nil {
		return m.InReplyToUserId
	}
	return 0
}

func (m *TweetResponse) GetInReplyToUserIdStr() string {
	if m != nil {
		return m.InReplyToUserIdStr
	}
	return ""
}

func (m *TweetResponse) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *TweetResponse) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *TweetResponse) GetPossiblySensitive() bool {
	if m != nil {
		return m.PossiblySensitive
	}
	return false
}

func (m *TweetResponse) GetRetweetCount() int64 {
	if m != nil {
		return m.RetweetCount
	}
	return 0
}

func (m *TweetResponse) GetRetweeted() bool {
	if m != nil {
		return m.Retweeted
	}
	return false
}

func (m *TweetResponse) GetRetweetedStatus() *Tweet {
	if m != nil {
		return m.RetweetedStatus
	}
	return nil
}

func (m *TweetResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TweetResponse) GetScopes() map[string]string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *TweetResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TweetResponse) GetTruncated() bool {
	if m != nil {
		return m.Truncated
	}
	return false
}

func (m *TweetResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *TweetResponse) GetWithheldCopyright() bool {
	if m != nil {
		return m.WithheldCopyright
	}
	return false
}

func (m *TweetResponse) GetWithheldInCountries() []string {
	if m != nil {
		return m.WithheldInCountries
	}
	return nil
}

func (m *TweetResponse) GetWithheldScope() string {
	if m != nil {
		return m.WithheldScope
	}
	return ""
}

func init() {
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*Contributor)(nil), "Contributor")
	proto.RegisterType((*Coordinates)(nil), "Coordinates")
	proto.RegisterType((*Hashtag)(nil), "Hashtag")
	proto.RegisterType((*Url)(nil), "Url")
	proto.RegisterType((*Mention)(nil), "Mention")
	proto.RegisterType((*MediaSize)(nil), "MediaSize")
	proto.RegisterType((*Sizes)(nil), "Sizes")
	proto.RegisterType((*Variant)(nil), "Variant")
	proto.RegisterType((*VideoInfo)(nil), "VideoInfo")
	proto.RegisterType((*Media)(nil), "Media")
	proto.RegisterType((*Entities)(nil), "Entities")
	proto.RegisterType((*BoundingBox)(nil), "BoundingBox")
	proto.RegisterType((*ContainedWithin)(nil), "ContainedWithin")
	proto.RegisterType((*Place)(nil), "Place")
	proto.RegisterType((*Tweet)(nil), "Tweet")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*TweetRequest)(nil), "TweetRequest")
	proto.RegisterType((*TweetResponse)(nil), "TweetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	Tweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Tweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error) {
	out := new(TweetResponse)
	err := grpc.Invoke(ctx, "/Api/Tweet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Tweet(context.Context, *TweetRequest) (*TweetResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Tweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Tweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/Tweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Tweet(ctx, req.(*TweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tweet",
			Handler:    _Api_Tweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/micro/twitter-srv/proto/api/api.proto",
}

func init() { proto.RegisterFile("github.com/micro/twitter-srv/proto/api/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xdd, 0x72, 0x1b, 0xb7,
	0xf5, 0xff, 0x53, 0x14, 0x29, 0xf2, 0x90, 0xd4, 0x07, 0x64, 0xd9, 0x2b, 0xd9, 0x8e, 0x15, 0xda,
	0x4e, 0x64, 0x27, 0xa6, 0x6c, 0xe5, 0x5f, 0x27, 0x6d, 0xa6, 0x93, 0xda, 0x1a, 0x77, 0xa2, 0x8e,
	0xdd, 0xba, 0x2b, 0x29, 0xed, 0xf4, 0x66, 0x67, 0xb9, 0x0b, 0x52, 0x18, 0x83, 0x00, 0x0b, 0x60,
	0xf5, 0xe1, 0x99, 0x4e, 0x9f, 0xa1, 0xd7, 0x7d, 0x80, 0xde, 0xb5, 0x97, 0x7d, 0xa0, 0xde, 0xf4,
	0xba, 0x4f, 0xd0, 0xc1, 0x01, 0x76, 0xb9, 0xa4, 0x28, 0x3b, 0x99, 0x49, 0xef, 0x7c, 0xa1, 0x19,
	0xee, 0xef, 0x9c, 0x83, 0x3d, 0x38, 0x1f, 0xbf, 0x03, 0xac, 0xe0, 0xf1, 0x90, 0x99, 0x93, 0xac,
	0xdf, 0x4b, 0xe4, 0x68, 0x77, 0xc4, 0x12, 0x25, 0x77, 0xcd, 0x19, 0x33, 0x86, 0xaa, 0x47, 0x5a,
	0x9d, 0xee, 0x8e, 0x95, 0x34, 0x72, 0x37, 0x1e, 0x33, 0xfb, 0xd7, 0xc3, 0xa7, 0xee, 0x67, 0x50,
	0x7b, 0x2d, 0x99, 0x30, 0x64, 0x15, 0xaa, 0x3c, 0x36, 0x41, 0x65, 0xbb, 0xb2, 0x53, 0x09, 0xed,
	0x4f, 0x44, 0xc4, 0x30, 0x58, 0xf0, 0x88, 0x18, 0x76, 0x8f, 0xa1, 0xb5, 0x2f, 0x85, 0x51, 0xac,
	0x9f, 0x19, 0xa9, 0xc8, 0x32, 0x2c, 0xb0, 0x14, 0x2d, 0xaa, 0xe1, 0x02, 0x4b, 0xc9, 0x06, 0xd4,
	0x59, 0x1a, 0x69, 0xa3, 0xd0, 0xa6, 0x19, 0xd6, 0x58, 0x7a, 0x68, 0x14, 0xb9, 0x03, 0x2d, 0x9d,
	0x28, 0x4a, 0x45, 0x24, 0xe2, 0x11, 0x0d, 0xaa, 0x28, 0x03, 0x07, 0xfd, 0x3a, 0x1e, 0xd1, 0xee,
	0xbe, 0x5d, 0x56, 0xaa, 0x94, 0x89, 0xd8, 0x50, 0x4d, 0xb6, 0xa1, 0x95, 0x4c, 0x1e, 0x83, 0xca,
	0x76, 0x75, 0xa7, 0x12, 0x96, 0x21, 0x42, 0x60, 0xd1, 0x5c, 0x8c, 0xa9, 0x7f, 0x0d, 0xfe, 0xee,
	0x7e, 0x09, 0x4b, 0xdf, 0xc6, 0xfa, 0xc4, 0xc4, 0x43, 0x12, 0xc0, 0x12, 0x13, 0x29, 0x4b, 0xbc,
	0x71, 0x35, 0xcc, 0x1f, 0xd1, 0x90, 0x9e, 0x9b, 0xc2, 0x90, 0x9e, 0x9b, 0x6e, 0x06, 0xd5, 0x63,
	0xc5, 0xdf, 0x61, 0xb4, 0x0a, 0xd5, 0x4c, 0x71, 0x6f, 0x63, 0x7f, 0xda, 0x1d, 0xa5, 0x4c, 0x8f,
	0x79, 0x7c, 0x11, 0x59, 0x89, 0xdf, 0x91, 0x87, 0xec, 0x62, 0x1f, 0x43, 0x9b, 0x9e, 0x8f, 0x63,
	0x91, 0xd2, 0x14, 0x35, 0x16, 0x51, 0xa3, 0x95, 0x63, 0xc7, 0x8a, 0x77, 0xff, 0x0c, 0x4b, 0xaf,
	0xa8, 0x30, 0x4c, 0x0a, 0xeb, 0x15, 0x46, 0xa6, 0xe2, 0xbc, 0xb2, 0xbf, 0xcb, 0xee, 0x2c, 0x4c,
	0xbb, 0xf3, 0xbe, 0x70, 0xfa, 0xb4, 0x2c, 0xce, 0x49, 0x4b, 0xad, 0x94, 0x96, 0xee, 0x37, 0xd0,
	0x7c, 0x45, 0x53, 0x16, 0x1f, 0xb2, 0xb7, 0x94, 0xb4, 0xa1, 0x72, 0xe6, 0x33, 0x59, 0x39, 0xb3,
	0x4f, 0x27, 0xb8, 0xdf, 0x6a, 0x58, 0x39, 0x21, 0xd7, 0xa1, 0xae, 0xa8, 0x66, 0x6f, 0xf3, 0x77,
	0xf9, 0xa7, 0xee, 0x5f, 0x2a, 0x50, 0xb3, 0xc6, 0x9a, 0x74, 0xa1, 0x3e, 0xa2, 0x29, 0xcb, 0x46,
	0xb8, 0x44, 0x6b, 0x0f, 0x7a, 0xc5, 0xca, 0xa1, 0x97, 0x90, 0x6d, 0xa8, 0x99, 0x93, 0x6c, 0xd4,
	0xc7, 0x75, 0xa7, 0x55, 0x9c, 0xc0, 0x6a, 0xe8, 0x51, 0xcc, 0x5d, 0x3c, 0x67, 0x34, 0x50, 0x60,
	0x35, 0x78, 0xac, 0x86, 0x14, 0x37, 0x37, 0xa3, 0x81, 0x82, 0xee, 0xef, 0x61, 0xe9, 0xbb, 0x58,
	0xb1, 0x58, 0x18, 0x1b, 0xc1, 0x3e, 0x33, 0x2a, 0x36, 0xd4, 0x6f, 0x2c, 0x7f, 0xb4, 0xd9, 0x49,
	0xa4, 0x30, 0x54, 0x98, 0xa8, 0x54, 0x46, 0x2d, 0x8f, 0x1d, 0x5d, 0x8c, 0x69, 0x9e, 0xf3, 0x6a,
	0x91, 0xf3, 0xee, 0x9f, 0xa0, 0xf9, 0x1d, 0x4b, 0xa9, 0x3c, 0x10, 0x03, 0x69, 0x57, 0x88, 0xf5,
	0x98, 0x26, 0x26, 0x52, 0xb1, 0x61, 0xd2, 0x57, 0x4c, 0xcb, 0x61, 0xa1, 0x85, 0xc8, 0xa7, 0xb0,
	0x92, 0x66, 0x28, 0x15, 0xd1, 0x88, 0x71, 0xce, 0xb4, 0x8f, 0xe8, 0x72, 0x0e, 0xbf, 0x42, 0x94,
	0xdc, 0x83, 0xc6, 0xa9, 0x73, 0x59, 0x07, 0xd5, 0xed, 0xea, 0x4e, 0x6b, 0xaf, 0xd1, 0xf3, 0x7b,
	0x08, 0x0b, 0x49, 0xf7, 0xaf, 0x55, 0xa8, 0xe1, 0x6e, 0xbf, 0x6f, 0xd7, 0xdd, 0x84, 0xa6, 0x8d,
	0x7c, 0x5c, 0xaa, 0xd0, 0x06, 0x02, 0xb6, 0x3e, 0x3f, 0x81, 0x95, 0x42, 0x18, 0x9d, 0x18, 0x33,
	0xd6, 0xbe, 0x44, 0x3b, 0xb9, 0xca, 0xb7, 0x16, 0xcc, 0xc3, 0x50, 0xbb, 0xb2, 0xf4, 0xeb, 0xef,
	0x2d, 0xfd, 0xa5, 0x4b, 0xa5, 0x4f, 0x6e, 0x41, 0xcd, 0x16, 0x90, 0x0e, 0x1a, 0x98, 0xc6, 0x7a,
	0x0f, 0xab, 0x28, 0x74, 0x20, 0xd9, 0x81, 0x55, 0x2d, 0x33, 0x95, 0xd0, 0x48, 0x9b, 0xd8, 0x64,
	0x3a, 0x62, 0x69, 0xd0, 0x74, 0x91, 0x73, 0xf8, 0x21, 0xc2, 0x07, 0x29, 0xd9, 0x85, 0x6b, 0xb3,
	0x9a, 0x18, 0x07, 0xc0, 0x57, 0xae, 0x4d, 0x6b, 0xdb, 0x98, 0xe4, 0xbc, 0xd1, 0x9a, 0xf0, 0x46,
	0xb9, 0xd1, 0xda, 0xd3, 0x8d, 0xf6, 0x00, 0xe0, 0xd4, 0x66, 0x3c, 0x62, 0x62, 0x20, 0x83, 0x8e,
	0x2f, 0xb9, 0xa2, 0x08, 0xc2, 0xe6, 0x69, 0xfe, 0xb3, 0xfb, 0x8f, 0x0a, 0x34, 0x5e, 0x08, 0xc3,
	0x0c, 0xa3, 0x98, 0xd0, 0x13, 0xc7, 0x44, 0x8e, 0x4a, 0x6c, 0x42, 0x3d, 0x35, 0x85, 0x85, 0x84,
	0x04, 0xb0, 0x98, 0x29, 0xee, 0xba, 0xbb, 0xb5, 0xb7, 0xd8, 0x3b, 0x56, 0x3c, 0x44, 0x84, 0x5c,
	0x9f, 0xd4, 0x5e, 0x2e, 0xc0, 0xd0, 0x3f, 0x82, 0x4e, 0xa6, 0xa9, 0x8a, 0x46, 0x8e, 0x36, 0x6c,
	0xca, 0xdc, 0xe2, 0x9e, 0x47, 0xc2, 0xb6, 0x15, 0xfb, 0x07, 0x6d, 0xa3, 0x8c, 0xc9, 0x0c, 0x6a,
	0xa8, 0x56, 0x77, 0xcd, 0x12, 0x3a, 0xb0, 0xfb, 0x5b, 0x68, 0x3d, 0x97, 0x99, 0x48, 0x99, 0x18,
	0x3e, 0x97, 0xe7, 0xa4, 0x77, 0x99, 0x73, 0x5b, 0x7b, 0xed, 0x5e, 0x89, 0x96, 0xdf, 0xcf, 0xc0,
	0xff, 0x59, 0x80, 0x15, 0x3b, 0x1e, 0x62, 0x26, 0x68, 0xfa, 0x3b, 0x66, 0x4e, 0x98, 0x20, 0xbf,
	0x00, 0x88, 0x8d, 0x1b, 0x18, 0xc5, 0xb2, 0xdb, 0xbd, 0x19, 0xad, 0xde, 0xb3, 0x42, 0xe5, 0x85,
	0x30, 0xea, 0x22, 0x2c, 0xd9, 0x90, 0x5d, 0x68, 0xf7, 0xbd, 0xa3, 0x51, 0x5f, 0x9e, 0x7b, 0xfa,
	0x68, 0xf7, 0x4a, 0xde, 0x87, 0xad, 0x7e, 0x69, 0x2b, 0x01, 0x2c, 0x25, 0x32, 0xb3, 0xeb, 0xf8,
	0xb2, 0xcf, 0x1f, 0x5d, 0xdf, 0xe3, 0xcf, 0x28, 0x91, 0x29, 0xcd, 0x59, 0xd9, 0x63, 0xfb, 0x32,
	0xa5, 0xb6, 0x6b, 0x06, 0x19, 0xe7, 0x8e, 0x5a, 0x5d, 0xd9, 0x37, 0x2c, 0x50, 0x22, 0x56, 0x57,
	0xf2, 0xb6, 0xf3, 0x72, 0xde, 0x5e, 0x2a, 0xf1, 0xf6, 0x6d, 0x80, 0x31, 0x8f, 0x13, 0xea, 0x98,
	0xa5, 0x81, 0x92, 0x26, 0x22, 0x65, 0x5e, 0x69, 0x16, 0x0d, 0xb5, 0xf5, 0x73, 0x58, 0x99, 0xd9,
	0xbe, 0x55, 0x7a, 0x43, 0x2f, 0xfc, 0x38, 0xb0, 0x3f, 0xc9, 0x35, 0xa8, 0x9d, 0xc6, 0x3c, 0xcb,
	0xe3, 0xed, 0x1e, 0x7e, 0xb6, 0xf0, 0x55, 0xa5, 0xfb, 0xaf, 0x2a, 0xd4, 0x5e, 0xdb, 0xe5, 0xc9,
	0xd3, 0x39, 0xa1, 0xbe, 0xde, 0x43, 0xd9, 0x8f, 0x1b, 0xe0, 0xaf, 0x61, 0x35, 0xc9, 0x13, 0x18,
	0x9d, 0x61, 0x06, 0x3d, 0x71, 0xad, 0xce, 0x66, 0x36, 0x5c, 0x49, 0x66, 0x0a, 0xa2, 0x94, 0x9d,
	0xc5, 0x77, 0x67, 0xa7, 0xf6, 0x9e, 0xec, 0xd4, 0x67, 0xb2, 0xb3, 0x03, 0x8d, 0x21, 0x95, 0x23,
	0x6a, 0x97, 0x5e, 0x9a, 0xb3, 0x87, 0x42, 0xea, 0xf3, 0xd8, 0xb8, 0x94, 0xc7, 0xe6, 0x95, 0x79,
	0x84, 0xd9, 0x3c, 0xde, 0x82, 0xe6, 0x58, 0xf2, 0x0b, 0xce, 0x04, 0xd5, 0x41, 0x6b, 0xbb, 0x8a,
	0xd2, 0x1c, 0xc8, 0xb3, 0xdc, 0xfe, 0xd1, 0xb2, 0xfc, 0xb7, 0x26, 0xd4, 0x8e, 0xce, 0x28, 0x35,
	0xe4, 0xb1, 0x9b, 0x5d, 0xfe, 0x08, 0x56, 0xee, 0xd4, 0x02, 0x0c, 0xa7, 0x34, 0x66, 0x5b, 0x3b,
	0x4f, 0xef, 0x95, 0xad, 0x7d, 0x1b, 0x20, 0x51, 0x34, 0x36, 0x34, 0x8d, 0x62, 0xe3, 0x5b, 0xa8,
	0xe9, 0x91, 0x67, 0x86, 0xdc, 0x87, 0x06, 0xf5, 0x4c, 0xe7, 0xc7, 0x70, 0xb3, 0x97, 0x53, 0x5f,
	0x58, 0x88, 0xc8, 0x53, 0x58, 0xa3, 0xe7, 0x86, 0xe2, 0x18, 0x28, 0xf4, 0x6b, 0xb3, 0xfa, 0xab,
	0xb9, 0x4e, 0x41, 0x9e, 0xf7, 0x61, 0x79, 0x10, 0x9f, 0x4a, 0xc5, 0x0c, 0x8d, 0x30, 0xf5, 0x98,
	0xe7, 0x6a, 0xd8, 0xc9, 0xd1, 0x7d, 0x0b, 0xda, 0xf8, 0xe7, 0x40, 0x8a, 0xd9, 0x6e, 0x84, 0x13,
	0xc0, 0x96, 0xd2, 0x80, 0x71, 0x43, 0x55, 0xc4, 0xe9, 0x29, 0xe5, 0x3e, 0xd5, 0x2d, 0x87, 0xbd,
	0xb4, 0x90, 0xaf, 0x81, 0xe6, 0x9c, 0x29, 0x0a, 0xe5, 0x29, 0xfa, 0xff, 0x70, 0x83, 0x89, 0x48,
	0xd1, 0x31, 0xbf, 0x88, 0x8c, 0x8c, 0xca, 0x07, 0x2f, 0x37, 0x44, 0xd6, 0x99, 0x08, 0xad, 0xf4,
	0x48, 0x1e, 0x4e, 0x4e, 0x60, 0x8f, 0x61, 0x63, 0xca, 0xaa, 0x98, 0x63, 0x6d, 0x7c, 0xdf, 0xda,
	0xc4, 0x26, 0x1f, 0x65, 0x5f, 0xc2, 0xe6, 0x5c, 0x0b, 0xf4, 0xa8, 0x83, 0x6f, 0xba, 0x76, 0xc9,
	0xca, 0x3a, 0xf8, 0x39, 0xac, 0x97, 0x0d, 0x71, 0x40, 0xb0, 0x34, 0x58, 0xc6, 0x17, 0xad, 0x14,
	0x26, 0xc7, 0x9a, 0xaa, 0x83, 0x94, 0x7c, 0x31, 0xbd, 0x1d, 0xaf, 0x8d, 0x2f, 0x59, 0xc1, 0x97,
	0x90, 0x19, 0x0b, 0x3f, 0x35, 0x79, 0x2c, 0x86, 0xc1, 0xaa, 0x6b, 0x0f, 0xfb, 0xdb, 0x0e, 0x17,
	0x6c, 0x86, 0x60, 0xcd, 0x8f, 0x70, 0xe4, 0x99, 0xd0, 0x81, 0xe4, 0x11, 0x90, 0xb1, 0xd4, 0x9a,
	0xf5, 0xf9, 0x45, 0xa4, 0xa9, 0xd0, 0xcc, 0xb0, 0x53, 0x1a, 0x10, 0x4c, 0xd3, 0x5a, 0x2e, 0x39,
	0xcc, 0x05, 0xe4, 0x2e, 0x74, 0x14, 0x35, 0xb6, 0xbc, 0x7d, 0xca, 0xd7, 0xd1, 0xfb, 0xb6, 0x07,
	0x8b, 0x8c, 0xfb, 0x67, 0x9a, 0x06, 0xd7, 0x5c, 0xc6, 0x0b, 0x80, 0x3c, 0x81, 0xd5, 0xe2, 0xc1,
	0x47, 0x2f, 0xd8, 0xf0, 0xae, 0x61, 0xe3, 0x84, 0x2b, 0x85, 0xdc, 0x85, 0xcf, 0x1e, 0x6b, 0xdd,
	0x09, 0x21, 0xb8, 0xee, 0x8e, 0xb5, 0xee, 0x89, 0x3c, 0x84, 0xba, 0x4e, 0xe4, 0x98, 0xea, 0xe0,
	0x06, 0xf6, 0x16, 0x71, 0x0b, 0xf4, 0x0e, 0x11, 0x74, 0xfc, 0xe9, 0x35, 0x8a, 0xfb, 0x44, 0x30,
	0xb9, 0x4f, 0x58, 0x47, 0x8d, 0xca, 0x44, 0x62, 0xfb, 0x25, 0xd8, 0x74, 0x8e, 0x16, 0x00, 0xd9,
	0x84, 0x45, 0x1b, 0xf5, 0x60, 0x0b, 0x9d, 0xab, 0xf5, 0x6c, 0x98, 0x43, 0x84, 0x6c, 0xd4, 0x2c,
	0x9b, 0x9e, 0x50, 0x9e, 0x46, 0x89, 0x1c, 0x5f, 0x28, 0x36, 0x3c, 0x31, 0xc1, 0x4d, 0x17, 0xb5,
	0x5c, 0xb2, 0x9f, 0x0b, 0xc8, 0x1e, 0x6c, 0x14, 0xea, 0x4c, 0xb8, 0xc8, 0x29, 0xdb, 0x65, 0xb7,
	0x90, 0x8e, 0xd6, 0x73, 0xe1, 0x81, 0xd8, 0xcf, 0x45, 0xb6, 0xbb, 0x0a, 0x1b, 0xdc, 0x42, 0x70,
	0xdb, 0x1d, 0xfb, 0x72, 0x14, 0x37, 0xb9, 0xf5, 0x53, 0x68, 0x95, 0x76, 0xfb, 0x83, 0x98, 0xea,
	0xdf, 0x1d, 0x58, 0xb4, 0x7b, 0x22, 0x4f, 0xe0, 0x5a, 0x99, 0x86, 0x22, 0x2a, 0xe2, 0x3e, 0xa7,
	0xee, 0xe0, 0xda, 0x08, 0xd7, 0xcb, 0xb2, 0x17, 0x4e, 0x34, 0xc3, 0x3c, 0x0b, 0xb3, 0xcc, 0x63,
	0x4f, 0xd4, 0x74, 0x10, 0x67, 0xdc, 0x44, 0x63, 0x25, 0x07, 0x8c, 0xbb, 0x0b, 0x49, 0x23, 0x5c,
	0xf6, 0xf0, 0x6b, 0x87, 0xda, 0xc8, 0xcc, 0x28, 0x46, 0x6c, 0x14, 0xfb, 0x6b, 0x43, 0x23, 0x5c,
	0x9f, 0x56, 0x3f, 0xb0, 0x22, 0x7b, 0xe9, 0x4c, 0xa9, 0x4e, 0x14, 0x1b, 0xdb, 0xd3, 0x53, 0x3e,
	0x7c, 0x4a, 0xd0, 0x14, 0xf1, 0xd5, 0xaf, 0x26, 0xbe, 0x07, 0xb0, 0x6a, 0x89, 0x28, 0xb3, 0x4c,
	0xa4, 0x7d, 0x3d, 0x2f, 0xb9, 0x6e, 0x9c, 0xe0, 0xae, 0xa4, 0x7b, 0xb0, 0x3e, 0x90, 0x9c, 0xcb,
	0xb3, 0x48, 0xd1, 0x3f, 0x66, 0x54, 0x1b, 0xdb, 0x2c, 0x06, 0xd9, 0xaa, 0x11, 0xae, 0x39, 0x51,
	0xe8, 0x24, 0x87, 0x54, 0x60, 0x00, 0x1c, 0x48, 0x55, 0xbe, 0xb2, 0x3f, 0x18, 0x17, 0xf0, 0x84,
	0x1d, 0x11, 0x61, 0x62, 0x88, 0x7c, 0x66, 0xd9, 0x31, 0x07, 0x6c, 0xbb, 0x0d, 0x14, 0xa3, 0x22,
	0xcd, 0x17, 0x69, 0xb9, 0x76, 0xf3, 0xa0, 0x5b, 0xe2, 0x0e, 0xb4, 0x86, 0x54, 0x16, 0x59, 0x6b,
	0xe3, 0x22, 0x30, 0xa4, 0x32, 0x4f, 0x96, 0x23, 0xd0, 0xce, 0x1c, 0x02, 0x5d, 0x2e, 0x13, 0xe8,
	0x5d, 0xe8, 0x30, 0x1d, 0x19, 0x15, 0x0b, 0xcd, 0x63, 0x23, 0x1d, 0xcf, 0x34, 0xc2, 0x36, 0xd3,
	0x47, 0x05, 0x36, 0x97, 0x61, 0x3e, 0x86, 0x36, 0x67, 0xda, 0xd6, 0x82, 0x73, 0x72, 0x0d, 0xdf,
	0xd4, 0x72, 0x98, 0xf3, 0x71, 0x0b, 0x1a, 0x5c, 0x26, 0x78, 0x97, 0x42, 0x72, 0x69, 0x86, 0xc5,
	0x73, 0x31, 0xd3, 0xd7, 0x4b, 0x33, 0xfd, 0x1e, 0x74, 0x84, 0x34, 0x6c, 0xc0, 0x9c, 0x8e, 0xf6,
	0x34, 0x32, 0x0d, 0x92, 0xaf, 0x20, 0xc8, 0xab, 0xa6, 0x1f, 0x27, 0x6f, 0x86, 0xca, 0x9e, 0x21,
	0xa2, 0x44, 0x72, 0xa9, 0x90, 0x52, 0x9a, 0xe1, 0x75, 0x2f, 0x7f, 0x5e, 0x88, 0xf7, 0xad, 0x94,
	0x7c, 0x03, 0xb7, 0xe6, 0x58, 0x62, 0xe9, 0xe1, 0x55, 0xc8, 0xf1, 0xcc, 0xe6, 0x25, 0x6b, 0xac,
	0x40, 0x7b, 0x31, 0xfa, 0x15, 0x74, 0xdf, 0xb5, 0x80, 0xbf, 0xa9, 0xdd, 0xc0, 0x65, 0x3e, 0xba,
	0x72, 0x19, 0x77, 0x75, 0x7b, 0x0a, 0x37, 0xe6, 0xac, 0x65, 0x6c, 0xd7, 0x04, 0xb8, 0xed, 0x8d,
	0x4b, 0x0b, 0x1c, 0xd9, 0xe6, 0xf9, 0x1c, 0xc8, 0xc4, 0x4e, 0x08, 0xaa, 0xd0, 0xf5, 0x4d, 0x7c,
	0xe7, 0x6a, 0x61, 0x62, 0x05, 0xd6, 0xe3, 0x87, 0xb0, 0x36, 0xd5, 0x62, 0xa8, 0xbc, 0x85, 0xca,
	0x2b, 0xe3, 0x52, 0x7f, 0x59, 0xdd, 0x9f, 0x4c, 0x3c, 0x9a, 0xdd, 0xd2, 0x4d, 0x37, 0xe1, 0x66,
	0x2c, 0xdc, 0x46, 0x4a, 0x0e, 0x71, 0x26, 0xde, 0xf8, 0x4c, 0xdc, 0x9a, 0x72, 0xe8, 0x25, 0x13,
	0x6f, 0x2e, 0xe5, 0x40, 0xb3, 0x94, 0xf6, 0x63, 0x15, 0xf5, 0xa5, 0x4a, 0xa9, 0xf2, 0x76, 0xb7,
	0xa7, 0x72, 0x70, 0xe8, 0x54, 0x9e, 0xa3, 0x86, 0x5b, 0xe0, 0x6b, 0xd8, 0x9a, 0x5d, 0x60, 0xc0,
	0x38, 0xf7, 0xe6, 0x1f, 0xa1, 0xf9, 0x8d, 0x69, 0xf3, 0x5f, 0x32, 0xce, 0x9d, 0x71, 0xc9, 0x57,
	0x3b, 0x0b, 0xbc, 0xd1, 0x9d, 0x29, 0x5f, 0x8f, 0xe8, 0xb9, 0xb9, 0xe4, 0x6b, 0xa6, 0x2f, 0xa7,
	0x3c, 0xd8, 0xc6, 0x3c, 0xe5, 0xbe, 0x1e, 0xeb, 0xd9, 0x5c, 0xe3, 0x29, 0x54, 0x49, 0x43, 0x13,
	0x3b, 0x6a, 0x3e, 0x76, 0x7d, 0x5e, 0x00, 0xb3, 0x1f, 0x8a, 0xba, 0x97, 0x3e, 0x14, 0x3d, 0x81,
	0x0d, 0x7d, 0x22, 0xcf, 0xa2, 0x98, 0xf3, 0x88, 0x09, 0x7b, 0x74, 0x8d, 0xdc, 0x8d, 0xf1, 0x2e,
	0x2e, 0x45, 0xac, 0xf0, 0x19, 0xe7, 0x07, 0x28, 0x72, 0x1f, 0x1f, 0x3e, 0x82, 0xba, 0x9f, 0xae,
	0xf7, 0xa6, 0xa6, 0xab, 0x47, 0xed, 0x80, 0x71, 0xbf, 0x0a, 0xee, 0xbb, 0xef, 0x8e, 0x6f, 0x39,
	0xea, 0x3a, 0xf7, 0x26, 0x34, 0x0d, 0x1b, 0xd1, 0xe8, 0xad, 0x14, 0x34, 0xf8, 0xc4, 0xb5, 0xae,
	0x05, 0xfe, 0x20, 0x45, 0x71, 0x47, 0xfa, 0x74, 0xf2, 0xd1, 0xe1, 0x36, 0x40, 0x66, 0x92, 0x48,
	0x0e, 0x06, 0x9a, 0x9a, 0x60, 0x07, 0x57, 0x6c, 0x66, 0x26, 0xf9, 0x0d, 0x02, 0x96, 0x07, 0x4e,
	0xa9, 0x62, 0x03, 0x46, 0xd3, 0xe0, 0x01, 0xba, 0x5e, 0x3c, 0x5f, 0x3d, 0x25, 0x1f, 0xfe, 0x90,
	0x29, 0xf9, 0xd9, 0x9c, 0x29, 0xd9, 0xfd, 0xfb, 0x02, 0xb4, 0xdd, 0xee, 0x1d, 0x47, 0xe3, 0x89,
	0xc2, 0x05, 0xa7, 0xe2, 0x4f, 0x14, 0x2e, 0x28, 0x57, 0x1e, 0x07, 0xed, 0x88, 0x5b, 0x9c, 0x77,
	0x1c, 0x9c, 0x7f, 0x80, 0xaa, 0x5e, 0x75, 0x80, 0xba, 0x03, 0x4b, 0x3c, 0x36, 0x11, 0x17, 0x43,
	0x7f, 0x24, 0xaf, 0xf7, 0xf0, 0xa3, 0x6e, 0x58, 0xe7, 0xb1, 0x79, 0x29, 0x86, 0x64, 0x13, 0x1a,
	0xee, 0x36, 0xc3, 0x52, 0x3f, 0xda, 0x96, 0xf0, 0x19, 0x3f, 0xa2, 0xac, 0xe7, 0x1f, 0x74, 0xca,
	0xd7, 0x84, 0xba, 0x2b, 0x01, 0x2f, 0x2a, 0x7f, 0x9e, 0xb5, 0xb9, 0x53, 0x6c, 0x84, 0x87, 0x47,
	0x7f, 0xf4, 0x6e, 0x58, 0x00, 0xa7, 0x7e, 0xf1, 0xd5, 0x89, 0xa5, 0x3a, 0x68, 0x6c, 0x57, 0x77,
	0x16, 0xfd, 0x57, 0xa7, 0x83, 0x54, 0x77, 0xff, 0xd9, 0x84, 0x8e, 0x0f, 0x98, 0x1e, 0x4b, 0xa1,
	0xe9, 0x87, 0xdb, 0xcc, 0x87, 0xdb, 0xcc, 0x87, 0xdb, 0xcc, 0xff, 0xf4, 0x36, 0xb3, 0x37, 0x73,
	0x9b, 0xd9, 0xea, 0x4d, 0x75, 0xe0, 0x87, 0x5b, 0xcd, 0xf7, 0xb9, 0xd5, 0xec, 0xed, 0x42, 0xf5,
	0xd9, 0x98, 0x91, 0x9d, 0xfc, 0x2b, 0x4c, 0xa7, 0x57, 0x26, 0xfe, 0xad, 0xe5, 0xe9, 0xa0, 0x76,
	0xff, 0xaf, 0x5f, 0xc7, 0xff, 0xae, 0x7d, 0xf1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x04,
	0xc5, 0x87, 0x91, 0x1b, 0x00, 0x00,
}
