// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/twitter-srv/proto/api/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/twitter-srv/proto/api/api.proto

It has these top-level messages:
	Point
	Contributor
	Coordinates
	Hashtag
	Url
	Mention
	MediaSize
	Sizes
	Variant
	VideoInfo
	Media
	Entities
	BoundingBox
	ContainedWithin
	Place
	Tweet
	User
	TweetRequest
	TweetResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiService interface {
	Tweet(ctx context.Context, in *TweetRequest, opts ...client.CallOption) (*TweetResponse, error)
}

type apiService struct {
	c           client.Client
	serviceName string
}

func ApiServiceClient(serviceName string, c client.Client) ApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "api"
	}
	return &apiService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *apiService) Tweet(ctx context.Context, in *TweetRequest, opts ...client.CallOption) (*TweetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Api.Tweet", in)
	out := new(TweetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiHandler interface {
	Tweet(context.Context, *TweetRequest, *TweetResponse) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Api{hdlr}, opts...))
}

type Api struct {
	ApiHandler
}

func (h *Api) Tweet(ctx context.Context, in *TweetRequest, out *TweetResponse) error {
	return h.ApiHandler.Tweet(ctx, in, out)
}
